name: pre-merge-checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  initial_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check code using ruff
        uses: chartboost/ruff-action@v1

      - name: Check docstrings using interrogate
        run: |
          pip install interrogate
          if [ $(interrogate -c pyproject.toml -v . -f 100 | grep "FAILED" | wc -l) = 1 ]; then
             echo "necessary docstrings missing:"
             interrogate -vv . -f 100 
             exit 1
          fi

      - name: Check code formatting using black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "~= 22.6"

      - name: Check pyproject.toml matches setup.py
        run: |
          pip install poetry2setup
          poetry2setup > setup.py
          bash scripts/check-git-clean.sh

  standard_tests:
    needs: [initial_checks]
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3      

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and run tests
        run: |
          pip install -e .[test]
          make test-pip
          shell: bash  # Ensure using bash for cross-platform compatibility, especially on Windows
